apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtrack-mini
  labels:
    app: cloudtrack-mini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudtrack-mini
  template:
    metadata:
      labels:
        app: cloudtrack-mini
    spec:
      containers:
        - name: cloudtrack-mini
          image: 888563322742.dkr.ecr.ap-south-1.amazonaws.com/cloudtrack-mini:latest
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: eyJwYXlsb2FkIjoiaU9tL05wbzhQc2F5SnVrSzREck9rV2FDYi9DMWdrWC93MHB4eXZoazFRbmVpSkFORHlwdTBxUWdDN2xucGpNQ0pOelZqUVdhYkJ0VGhGeU5lR0ExOWFhT1Jrb0Z0djhnaURYRnJFbUp5TUNxaUd4NnJ0d2JGeGdocXBsOUFjSnZiVWFHS1Q5eDNrL2xWSk92K1hiSmM2SDlaWndWUmZpT2pTTGE1aEZZc3BuVUJsSC94eVZrN2hJN3VJZThRdFRnTkJvT2hIckh6YmNBZnZwbGlJa0VWQkFoNVUzeU9QZVZZYXNFYnZvZUtBczJNdC8rK0FBVk1NdUoweTBVekFHOWJ3VlJmZlZQTVZ4RUVZcW1ram8wZllrWUZmdVcxN2xNcXVvTW1TY1ZIYm5IUVZtL1lPS3dVUUFWUWdqWHN0czZWTXVrWVhmRDV1Rjl1WnI0aDhZS2JsVHFxcHJSdVVrZysyM0VCZXI1VFg5RHJwclNXN3h6Mi9zdG9jRmozQU5VSXFlU1piZ2tlSFlQME4yR3kyMVAxRlhSTHRublRiZm1HRkcwS1ZpTzIvaktUZzlxU0g4Q3RrZkJ6UlBRbDcrMjU4UWxVVllIMFQ2dlZGNk1jMDl4T3U5NEhNZGZnMEF4bDY3d3ZJM0R4bUw0aXhPVjRIdkdzRjRKVHFEbjUrNWVHWUlRSDZndmhzNVNYaVlzUnowL05mYmhpcW5Jazh6WW13dDZwUGNUdnN4K0VFTEo4eENIOHltZUZyVkpEQ1lwYXJsQzJpcW8raHhheWg4UnVDNnFqV0JQTDdlcW5Kb2lTaUZ2M0svMzdJS2FERzJvQnZ6T3ZHYXI4bFlVc05Md1lBMlBmcnJ2aDFRSXdTbWFrN3JGdzhodVB5cGtHY1A3Mm9IZDUyd2ZYWERjb3Z4Zk9vVWNTSUg4QmJESWpYckxTVjZPOEdsbkhmQjg4dURNUWo4UnlrOTgrQWRiYm1zR0xDNi9CSkE0dWRBR255bmNSbXFSNXl2TXVLbEgzRjlZM285RzNGYlRIcnc2SWNIUm9WWGZLYlFhNHlNdFJlQ3o0SzUyNkNCQWE2T1ByUGpScWZwUHRFMUZwSVhML0hGVjhSV3RiYWFuN1dXb2MvbW9yR2ZGeGlidW9EYlYxYkpEWnZaVm5JWE4xdWhlZ1U2bWZBdXQ2YXBNTkVHSkswaWtyQmtXeVJTd3ljaUFiOG4rYldsVXhlZ3E5WDl3R1NNREgvZzNMWmRtYVJGeENPcnBKY09QSFljTnMrRGVlb2ZTcXdXTUo4WTMvcWtmUXZjaXlqY1dldFE1Rko1SlVWMVZqWU83Sm5COUZWekkyQUJERjY0ei8vZll2TXcxNGo4TU9BPT0iLCJkYXRha2V5IjoiQVFJQkFIaUhXYVlUblJVV0NibnorN0x2TUcrQVB2VEh6SGxCVVE5RnFFbVYyNkJkd3dHN1BCTGIwMTh0UElEWlpJY2lMZnlsQUFBQWZqQjhCZ2txaGtpRzl3MEJCd2FnYnpCdEFnRUFNR2dHQ1NxR1NJYjNEUUVIQVRBZUJnbGdoa2dCWlFNRUFTNHdFUVFNaEpkeERhUDZwNWpIWUFLc0FnRVFnRHQ5RWpvaU1EeDMwMGlZZVgvZlZnV3UyVmZHSWxVVG1TUVJZVjJCVElCQkVVSCszaVErY3IvTzJSMWd0NzFOdTNNNVNvNnpaT1diTmFKYUFRPT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE3ODAxMjcyMzJ9
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: APP_NAME
              value: CloudTrack Mini
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
