apiVersion: v1
kind: Service
metadata:
  name: cloudtrack-mini
  labels:
    app: cloudtrack-mini
spec:
  type: NodePort
  selector:
    app: cloudtrack-mini
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
